# REUSE specification (https://reuse.software) — declares copyright and
# licensing for the whole tree without per-file SPDX headers, so the project
# is REUSE-compliant. The license text lives in LICENSES/Apache-2.0.txt.
version = 1

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Manuel Soto Calvo and Han Soo Lee"
SPDX-License-Identifier = "Apache-2.0"
